# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('time_user', models.DateTimeField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('floor', models.IntegerField(default=0)),
                ('message', models.TextField()),
            ],
        ),
    ]
